/*
 * TIMER0.c
 *
 * Created: 8/22/2023 5:34:26 PM
 *  Author: Ahmed ElSayed
 */ 
#include "TIMER0.h"

void TIMER0_Init(){
	/*set timer prescaler*/
	#if TIMER0_PRESCALER == TIMER0_NO_PRESCALE
	
	SET_BIT(TIMER0_CONTROL_R, TIMER0_CS00_BIT);
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_CS01_BIT);
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_CS02_BIT); 
	
	#elif TIMER0_PRESCALER == TIMER0_PRESCALE_8
	
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_CS00_BIT);
	SET_BIT(TIMER0_CONTROL_R, TIMER0_CS01_BIT);
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_CS02_BIT);
	
	#elif TIMER0_PRESCALER == TIMER0_PRESCALE_64
	
	SET_BIT(TIMER0_CONTROL_R, TIMER0_CS00_BIT);
	SET_BIT(TIMER0_CONTROL_R, TIMER0_CS01_BIT);
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_CS02_BIT);
	
	#elif TIMER0_PRESCALER == TIMER0_PRESCALE_256
	
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_CS00_BIT);
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_CS01_BIT);
	SET_BIT(TIMER0_CONTROL_R, TIMER0_CS02_BIT);
	
	#elif TIMER0_PRESCALER == TIMER0_PRESCALE_1024
	
	SET_BIT(TIMER0_CONTROL_R, TIMER0_CS00_BIT);
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_CS01_BIT);
	SET_BIT(TIMER0_CONTROL_R, TIMER0_CS02_BIT);
	
	#elif TIMER0_PRESCALER == TIMER0_EXTERNAL_FALLING_EDGE
	
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_CS00_BIT);
	SET_BIT(TIMER0_CONTROL_R, TIMER0_CS01_BIT);
	SET_BIT(TIMER0_CONTROL_R, TIMER0_CS02_BIT);
	
	#elif TIMER0_PRESCALER == TIMER0_EXTERNAL_RISING_EDGE
	
	SET_BIT(TIMER0_CONTROL_R, TIMER0_CS00_BIT);
	SET_BIT(TIMER0_CONTROL_R, TIMER0_CS01_BIT);
	SET_BIT(TIMER0_CONTROL_R, TIMER0_CS02_BIT);
	
	#else
	
	#error "Invalid prescaler used!"
	
	#endif /*PRESCALER*/
	
	/*set timer operation mode*/
	#if TIMER0_MODE == TIMER0_NORMAL
	
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_WGM00_BIT);
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_WGM01_BIT);
	
	#elif TIMER0_MODE == TIMER0_PHASE_CORRECTED_PWM
	
	SET_BIT(TIMER0_CONTROL_R, TIMER0_WGM00_BIT);
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_WGM01_BIT);
	
	#elif TIMER0_MODE == TIMER0_CTC
	
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_WGM00_BIT);
	SET_BIT(TIMER0_CONTROL_R, TIMER0_WGM01_BIT);
	
	#elif TIMER0_MODE == TIMER0_FAST_PWM
	
	SET_BIT(TIMER0_CONTROL_R, TIMER0_WGM00_BIT);
	SET_BIT(TIMER0_CONTROL_R, TIMER0_WGM01_BIT);
	
	#else
	
	#error "Invalid operation mode used!"
	
	#endif /*OPERATION MODE*/
	
	/*set OC0 pin operation*/
	#if TIMER0_OC0_OUTPUT_MODE == TIMER0_DISCONNECT_OC0
	
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_COM00_BIT);
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_COM01_BIT);
	
	#elif TIMER0_OC0_OUTPUT_MODE == TIMER0_TOGGLE_OC0
	
	SET_BIT(TIMER0_CONTROL_R, TIMER0_COM00_BIT);
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_COM01_BIT);
	
	#elif TIMER0_OC0_OUTPUT_MODE == TIMER0_CLEAR_OC0
	
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_COM00_BIT);
	SET_BIT(TIMER0_CONTROL_R, TIMER0_COM01_BIT);
	
	#elif TIMER0_OC0_OUTPUT_MODE == TIMER0_SET_OC0
	
	SET_BIT(TIMER0_CONTROL_R, TIMER0_COM00_BIT);
	SET_BIT(TIMER0_CONTROL_R, TIMER0_COM01_BIT);
	
	#else
	
	#error "Invalid OC0 pin mode used!"
	
	#endif /*OC0 PIN MODE*/
	
	INT_TIMER0_Init();
}

void TIMER0_OFF(){
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_CS00_BIT);
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_CS01_BIT);
	CLEAR_BIT(TIMER0_CONTROL_R, TIMER0_CS02_BIT);
}

UINT8_t TIMER0_Read(){
	return TIMER0_ACC_R;
}

void TIMER0_Write(UINT8_t val){
	TIMER0_COMP_R = val;	
}